#!/bin/sh
set -eu

env_file="${PROIDENTITY_ENV_FILE:-/etc/proidentity-mail/proidentity-mail.env}"
for key in \
	PROIDENTITY_MAIL_HOSTNAME \
	PROIDENTITY_PUBLIC_HOSTNAME \
	PROIDENTITY_ADMIN_HOSTNAME \
	PROIDENTITY_WEBMAIL_HOSTNAME \
	PROIDENTITY_DAV_HOSTNAME \
	PROIDENTITY_TLS_MODE \
	PROIDENTITY_PROXY_MODE \
	PROIDENTITY_TRUST_PROXY_HEADERS \
	PROIDENTITY_TRUSTED_PROXY_CIDRS
do
	grep "^${key}=" "$env_file" || true
done
