package webmail

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

const proidentitySieveScriptName = "proidentity.sieve"

type MailboxFilterSet struct {
	Email   string
	Filters []MailFilter
}

func (s MaildirStore) SyncFilters(ctx context.Context, email string, filters []MailFilter) error {
	local, domain, ok := strings.Cut(strings.ToLower(strings.TrimSpace(email)), "@")
	if !ok || local == "" || domain == "" {
		return errors.New("valid email is required")
	}
	home := filepath.Join(s.Root, domain, local)
	sieveDir := filepath.Join(home, "sieve")
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}
	if err := os.MkdirAll(sieveDir, 0750); err != nil {
		return err
	}
	script, err := renderSieveFilters(filters)
	if err != nil {
		return err
	}
	scriptPath := filepath.Join(sieveDir, proidentitySieveScriptName)
	if err := writeFileAtomic(scriptPath, []byte(script), 0640); err != nil {
		return err
	}
	return activateSieveScript(home)
}

func renderSieveFilters(filters []MailFilter) (string, error) {
	ordered := append([]MailFilter(nil), filters...)
	sort.SliceStable(ordered, func(i, j int) bool {
		return strings.ToLower(ordered[i].Name) < strings.ToLower(ordered[j].Name)
	})

	var builder strings.Builder
	builder.WriteString(`require ["fileinto", "body"];`)
	builder.WriteString("\n\n# Generated by ProIdentity Mail. Changes made here may be overwritten.\n")
	rendered := 0
	for _, filter := range ordered {
		if !filter.Enabled {
			continue
		}
		condition, err := sieveCondition(filter)
		if err != nil {
			return "", err
		}
		action, err := sieveAction(filter)
		if err != nil {
			return "", err
		}
		builder.WriteString("\n# ")
		builder.WriteString(sieveComment(filter.Name))
		builder.WriteString("\nif ")
		builder.WriteString(condition)
		builder.WriteString(" {\n  ")
		builder.WriteString(action)
		builder.WriteString("\n  stop;\n}\n")
		rendered++
	}
	if rendered == 0 {
		builder.WriteString("\n# No enabled ProIdentity filters.\n")
	}
	return builder.String(), nil
}

func sieveCondition(filter MailFilter) (string, error) {
	field := strings.ToLower(strings.TrimSpace(filter.Field))
	operator := strings.ToLower(strings.TrimSpace(filter.Operator))
	value := strings.TrimSpace(filter.Value)
	if value == "" {
		return "", errors.New("filter value is required")
	}
	match, value, err := sieveMatch(operator, value)
	if err != nil {
		return "", err
	}
	switch field {
	case "from":
		return fmt.Sprintf(`header %s "From" "%s"`, match, sieveString(value)), nil
	case "to":
		return fmt.Sprintf(`header %s ["To", "Cc", "Delivered-To", "Envelope-To"] "%s"`, match, sieveString(value)), nil
	case "subject":
		return fmt.Sprintf(`header %s "Subject" "%s"`, match, sieveString(value)), nil
	case "body":
		return fmt.Sprintf(`body :text %s "%s"`, match, sieveString(value)), nil
	default:
		return "", errors.New("filter field must be from, to, subject, or body")
	}
}

func sieveMatch(operator, value string) (string, string, error) {
	switch operator {
	case "contains", "":
		return ":contains", value, nil
	case "equals":
		return ":is", value, nil
	case "starts_with":
		return ":matches", value + "*", nil
	case "ends_with":
		return ":matches", "*" + value, nil
	default:
		return "", "", errors.New("filter operator must be contains, equals, starts_with, or ends_with")
	}
}

func sieveAction(filter MailFilter) (string, error) {
	switch strings.ToLower(strings.TrimSpace(filter.Action)) {
	case "move", "":
		folder, err := sieveMailbox(filter.Folder)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf(`fileinto "%s";`, sieveString(folder)), nil
	case "mark_spam":
		return `fileinto "Spam";`, nil
	case "delete":
		return "discard;", nil
	case "keep":
		return "keep;", nil
	default:
		return "", errors.New("filter action must be move, mark_spam, delete, or keep")
	}
}

func sieveMailbox(folder string) (string, error) {
	cleaned := strings.TrimPrefix(strings.TrimSpace(folder), ".")
	switch strings.ToLower(cleaned) {
	case "inbox":
		return "INBOX", nil
	case "drafts", "draft":
		return "Drafts", nil
	case "sent":
		return "Sent", nil
	case "spam", "junk":
		return "Spam", nil
	case "trash":
		return "Trash", nil
	case "archive":
		return "Archive", nil
	}
	if _, err := customMailboxName(cleaned); err != nil {
		return "", err
	}
	return cleaned, nil
}

func sieveString(value string) string {
	var builder strings.Builder
	for _, r := range value {
		switch r {
		case '\\':
			builder.WriteString(`\\`)
		case '"':
			builder.WriteString(`\"`)
		case '\r', '\n':
			builder.WriteByte(' ')
		default:
			if r >= 0 && r < 0x20 {
				continue
			}
			builder.WriteRune(r)
		}
	}
	return builder.String()
}

func sieveComment(value string) string {
	value = strings.ReplaceAll(strings.TrimSpace(value), "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	if value == "" {
		return "Filter"
	}
	return value
}

func writeFileAtomic(path string, data []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, "."+filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer func() { _ = os.Remove(tmpPath) }()
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(mode); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}

func activateSieveScript(home string) error {
	activePath := filepath.Join(home, ".dovecot.sieve")
	target := filepath.ToSlash(filepath.Join("sieve", proidentitySieveScriptName))
	if runtime.GOOS == "windows" {
		data, err := os.ReadFile(filepath.Join(home, filepath.FromSlash(target)))
		if err != nil {
			return err
		}
		return writeFileAtomic(activePath, data, 0640)
	}
	tmp := activePath + ".tmp"
	_ = os.Remove(tmp)
	if err := os.Symlink(target, tmp); err != nil {
		return err
	}
	return os.Rename(tmp, activePath)
}
