#!/usr/bin/env bash
set -euo pipefail

# ProIdentity Mail full server bootstrap.
#
# Expected artifact directory:
#   webadmin webmail groupware mailctl apply-mail-config
#
# Common overrides:
#   ARTIFACT_DIR=/tmp/proidentity-release
#   PUBLIC_IPV4=46.225.87.251
#   MAIL_HOSTNAME=mail.example.com
#   ADMIN_HOSTNAME=madmin.example.com
#   WEBMAIL_HOSTNAME=webmail.example.com
#   DAV_HOSTNAME=webmail.example.com
#   AUTOCONFIG_HOSTNAME=autoconfig.example.com
#   AUTODISCOVER_HOSTNAME=autodiscover.example.com
#   TLS_MODE=none|behind-proxy|letsencrypt-http|letsencrypt-dns-cloudflare|custom-cert
#   ADMIN_USERNAME=admin
#   ADMIN_PASSWORD=...
#   DB_NAME=proidentity_mail
#   DB_USER=proidentity_mail
#   DB_PASSWORD=...
#
# The same values can be provided as command-line options, for example:
#   ./proidentity-production-setup.sh \
#     --artifact-dir /tmp/proidentity-release \
#     --public-ipv4 46.225.87.251 \
#     --mail-hostname mail.example.com \
#     --admin-hostname madmin.example.com \
#     --webmail-hostname webmail.example.com \
#     --tls-mode letsencrypt-dns-cloudflare
#
# Passwords, DB credentials, auth-policy tokens, and backup encryption keys are
# autogenerated when not supplied by option, environment, or an existing env file.

ARTIFACT_DIR="${ARTIFACT_DIR:-/tmp/proidentity-release}"
ENV_DIR="/etc/proidentity-mail"
ENV_FILE="${ENV_FILE:-${ENV_DIR}/proidentity-mail.env}"
ADMIN_ENV_FILE="${ADMIN_ENV_FILE:-${ENV_DIR}/webadmin.env}"
WEBMAIL_ENV_FILE="${WEBMAIL_ENV_FILE:-${ENV_DIR}/webmail.env}"
GROUPWARE_ENV_FILE="${GROUPWARE_ENV_FILE:-${ENV_DIR}/groupware.env}"
BIN_DIR="/opt/proidentity-mail/bin"
SUMMARY_FILE="${SUMMARY_FILE:-/root/proidentity-install-summary.txt}"
BACKUP_ROOT="${BACKUP_ROOT:-/root/proidentity-backups}"
INSTALL_TS="$(date +%Y%m%d-%H%M%S)"

usage() {
  cat <<'USAGE'
Usage: proidentity-production-setup.sh [options]

Installs a complete ProIdentity Mail server:
  - MariaDB database and user
  - Postfix, Dovecot, Rspamd, ClamAV, Redis, Unbound, Nginx
  - webadmin, webmail, groupware/DAV, mailctl, config apply helper
  - systemd services/timers, backup job, TLS worker, config drift/apply queue
  - rendered mail/proxy configs and initial migrations

Options override environment variables and existing env-file values:
  --artifact-dir PATH              Directory containing webadmin, webmail, groupware, mailctl, apply-mail-config
  --mail-hostname HOST             Mail server hostname, usually mail.example.com
  --admin-hostname HOST            Admin UI hostname
  --webmail-hostname HOST          Webmail UI hostname
  --dav-hostname HOST              CalDAV/CardDAV hostname
  --autoconfig-hostname HOST       Thunderbird autoconfig hostname
  --autodiscover-hostname HOST     Outlook autodiscover hostname
  --public-hostname DOMAIN         Base public domain used for discovery defaults
  --public-ipv4 IP                 Public IPv4 used in generated DNS records
  --public-ipv6 IP                 Public IPv6 used in generated DNS records
  --tls-mode MODE                  none|behind-proxy|letsencrypt-http|letsencrypt-dns-cloudflare|custom-cert
  --proxy-mode MODE                internal-nginx
  --trust-proxy-headers BOOL       true when an upstream trusted proxy sets real IP headers
  --trusted-proxy-cidrs CIDRS      Comma-separated trusted proxy CIDRs
  --cloudflare-cert-domain DOMAIN  Cloudflare domain for DNS-01 certificate automation
  --cloudflare-credentials-file PATH
  --tls-cert-path PATH             Custom HTTPS/mail certificate path
  --tls-key-path PATH              Custom HTTPS/mail private key path
  --admin-username USER
  --admin-password PASSWORD        Autogenerated if omitted
  --db-name NAME                   Default: proidentity_mail
  --db-user USER                   Default: proidentity_mail
  --db-password PASSWORD           Autogenerated if omitted
  --backup-encryption-key SECRET   Autogenerated if omitted
  --auth-policy-token SECRET       Autogenerated if omitted
  --auth-policy-nonce SECRET       Autogenerated if omitted
  --env-file PATH
  --summary-file PATH
  --backup-root PATH
  -h, --help

Any omitted secret is generated with openssl and written to the root-only
summary file, default /root/proidentity-install-summary.txt.
USAGE
}

arg_value() {
  local current="$1"
  local next="${2:-}"
  if [[ "${current}" == *=* ]]; then
    printf '%s' "${current#*=}"
    return 0
  fi
  if [[ -z "${next}" || "${next}" == --* ]]; then
    echo "Missing value for ${current%%=*}" >&2
    exit 2
  fi
  printf '%s' "${next}"
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    local arg="$1"
    case "${arg}" in
      -h|--help)
        usage
        exit 0
        ;;
      --artifact-dir|--artifact-dir=*)
        ARTIFACT_DIR="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --mail-hostname|--mail-hostname=*)
        MAIL_HOSTNAME="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --admin-hostname|--admin-hostname=*)
        ADMIN_HOSTNAME="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --webmail-hostname|--webmail-hostname=*)
        WEBMAIL_HOSTNAME="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --dav-hostname|--dav-hostname=*)
        DAV_HOSTNAME="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --autoconfig-hostname|--autoconfig-hostname=*)
        AUTOCONFIG_HOSTNAME="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --autodiscover-hostname|--autodiscover-hostname=*)
        AUTODISCOVER_HOSTNAME="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --public-hostname|--public-hostname=*)
        PUBLIC_HOSTNAME="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --public-ipv4|--public-ipv4=*)
        PUBLIC_IPV4="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --public-ipv6|--public-ipv6=*)
        PUBLIC_IPV6="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --tls-mode|--tls-mode=*)
        TLS_MODE="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --proxy-mode|--proxy-mode=*)
        PROXY_MODE="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --trust-proxy-headers|--trust-proxy-headers=*)
        TRUST_PROXY_HEADERS="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --trusted-proxy-cidrs|--trusted-proxy-cidrs=*)
        TRUSTED_PROXY_CIDRS="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --cloudflare-cert-domain|--cloudflare-cert-domain=*)
        CLOUDFLARE_CERT_DOMAIN="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --cloudflare-credentials-file|--cloudflare-credentials-file=*)
        CLOUDFLARE_CREDENTIALS_FILE="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --tls-cert-path|--tls-cert-path=*)
        TLS_CERT_PATH="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --tls-key-path|--tls-key-path=*)
        TLS_KEY_PATH="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --admin-username|--admin-username=*)
        ADMIN_USERNAME="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --admin-password|--admin-password=*)
        ADMIN_PASSWORD="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --db-name|--db-name=*)
        DB_NAME="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --db-user|--db-user=*)
        DB_USER="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --db-password|--db-password=*)
        DB_PASSWORD="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --backup-encryption-key|--backup-encryption-key=*)
        BACKUP_ENCRYPTION_KEY="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --auth-policy-token|--auth-policy-token=*)
        AUTH_POLICY_TOKEN="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --auth-policy-nonce|--auth-policy-nonce=*)
        AUTH_POLICY_NONCE="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --env-file|--env-file=*)
        ENV_FILE="$(arg_value "${arg}" "${2:-}")"
        ENV_DIR="$(dirname "${ENV_FILE}")"
        ADMIN_ENV_FILE="${ENV_DIR}/webadmin.env"
        WEBMAIL_ENV_FILE="${ENV_DIR}/webmail.env"
        GROUPWARE_ENV_FILE="${ENV_DIR}/groupware.env"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --summary-file|--summary-file=*)
        SUMMARY_FILE="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      --backup-root|--backup-root=*)
        BACKUP_ROOT="$(arg_value "${arg}" "${2:-}")"
        [[ "${arg}" == *=* ]] || shift
        ;;
      *)
        echo "Unknown option: ${arg}" >&2
        usage >&2
        exit 2
        ;;
    esac
    shift
  done
}

parse_args "$@"

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root" >&2
  exit 1
fi

random_secret() {
  local bytes="${1:-32}"
  openssl rand -hex "${bytes}"
}

require_file() {
  local path="$1"
  if [[ ! -s "${path}" ]]; then
    echo "Required artifact missing: ${path}" >&2
    exit 2
  fi
}

validate_ident() {
  local name="$1"
  local value="$2"
  if [[ ! "${value}" =~ ^[A-Za-z0-9_]+$ ]]; then
    echo "${name} must contain only letters, numbers, and underscores" >&2
    exit 2
  fi
}

install_env_file() {
  local path="$1"
  local owner="$2"
  local group="$3"
  local mode="$4"
  install -m "${mode}" -o "${owner}" -g "${group}" /dev/null "${path}"
}

set_env_file() {
  local file="$1"
  local key="$2"
  local value="$3"
  local escaped
  escaped="$(printf '%s' "${value}" | sed 's/[\/&]/\\&/g')"
  if grep -q "^${key}=" "${file}" 2>/dev/null; then
    sed -i "s/^${key}=.*/${key}=${escaped}/" "${file}"
  else
    printf '%s=%s\n' "${key}" "${value}" >> "${file}"
  fi
}

set_env() {
  set_env_file "${ENV_FILE}" "$@"
}

sql_string() {
  local value="$1"
  value="$(printf '%s' "${value}" | sed "s/\\\\/\\\\\\\\/g; s/'/''/g")"
  printf "'%s'" "${value}"
}

detect_public_ipv4() {
  curl -fsS --max-time 5 https://api.ipify.org 2>/dev/null || true
}

discovery_base_from_mail_hostname() {
  local host="${1%.}"
  host="${host,,}"
  if [[ "${host}" == *.local || "${host}" != *.* ]]; then
    return
  fi
  if [[ "${host}" == mail.* ]]; then
    printf '%s' "${host#mail.}"
  fi
}

default_discovery_hostname() {
  local prefix="$1"
  local base="${PUBLIC_HOSTNAME}"
  if [[ -z "${base}" ]]; then
    base="$(discovery_base_from_mail_hostname "${MAIL_HOSTNAME}")"
  fi
  if [[ -n "${base}" ]]; then
    printf '%s.%s' "${prefix}" "${base}"
  fi
}

backup_existing() {
  local backup_dir="${BACKUP_ROOT}/${INSTALL_TS}-production-setup"
  install -d -m 0700 "${backup_dir}"
  for path in "${ENV_DIR}" /etc/systemd/system/proidentity-webadmin.service /etc/systemd/system/proidentity-webmail.service /etc/systemd/system/proidentity-groupware.service /etc/systemd/system/proidentity-backup.service /etc/systemd/system/proidentity-config-apply.service /etc/systemd/system/proidentity-config-apply.path /etc/nginx/conf.d/proidentity.conf /etc/postfix/main.cf /etc/dovecot/conf.d/99-proidentity.conf /etc/unbound/unbound.conf.d/proidentity-dnsbl.conf /etc/resolvconf/resolv.conf.d/head /etc/dhcp/dhclient.conf /etc/network/interfaces.d/50-cloud-init; do
    if [[ -e "${path}" ]]; then
      cp -a "${path}" "${backup_dir}/" 2>/dev/null || true
    fi
  done
  echo "${backup_dir}"
}

install_packages() {
  echo "Installing OS packages..."
  debconf-set-selections <<< "postfix postfix/mailname string ${MAIL_HOSTNAME}"
  debconf-set-selections <<< "postfix postfix/main_mailer_type select Internet Site"
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates curl openssl ssl-cert rsync dnsutils unbound dns-root-data \
    mariadb-server redis-server \
    postfix postfix-mysql \
    dovecot-core dovecot-imapd dovecot-pop3d dovecot-lmtpd dovecot-mysql dovecot-sieve dovecot-managesieved \
    rspamd clamav-daemon clamav-freshclam \
    nginx certbot python3-certbot-nginx python3-certbot-dns-cloudflare \
    sudo
}

configure_dns_resolver() {
  echo "Configuring local recursive DNS resolver for DNSBL checks..."
  install -d -m 0755 /etc/unbound/unbound.conf.d
  cat > /etc/unbound/unbound.conf.d/proidentity-dnsbl.conf <<'EOF'
server:
  interface: 127.0.0.1
  interface: ::1
  access-control: 127.0.0.0/8 allow
  access-control: ::1 allow
  do-ip4: yes
  do-ip6: yes
  do-udp: yes
  do-tcp: yes
  hide-identity: yes
  hide-version: yes
  harden-glue: yes
  harden-dnssec-stripped: yes
  qname-minimisation: yes
  prefetch: yes
  rrset-roundrobin: yes
EOF

  install -d -m 0755 /etc/resolvconf/resolv.conf.d
  cat > /etc/resolvconf/resolv.conf.d/head <<'EOF'
# ProIdentity local resolver for DNSBL; public DNS as fallback only
nameserver 127.0.0.1
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF

  if [[ -f /etc/dhcp/dhclient.conf ]]; then
    if grep -q "^supersede domain-name-servers" /etc/dhcp/dhclient.conf; then
      sed -i "s/^supersede domain-name-servers.*/supersede domain-name-servers 1.1.1.1, 8.8.8.8;/" /etc/dhcp/dhclient.conf
    else
      printf '\n# ProIdentity preferred public resolvers\nsupersede domain-name-servers 1.1.1.1, 8.8.8.8;\n' >> /etc/dhcp/dhclient.conf
    fi
  fi

  if [[ -f /etc/network/interfaces.d/50-cloud-init ]]; then
    sed -i 's/^\([[:space:]]*dns-nameservers\).*/\1 2606:4700:4700::1111 2001:4860:4860::8888/' /etc/network/interfaces.d/50-cloud-init || true
  fi

  unbound-checkconf
  systemctl enable --now unbound
  systemctl restart unbound
  if command -v resolvconf >/dev/null 2>&1; then
    printf 'nameserver 1.1.1.1\nnameserver 8.8.8.8\n' | resolvconf -a eth0.dhclient || true
    printf 'nameserver 2606:4700:4700::1111\nnameserver 2001:4860:4860::8888\n' | resolvconf -a eth0.inet6 || true
    resolvconf -u || true
  fi
}

ensure_users() {
  if ! getent group vmail >/dev/null; then
    groupadd --system --gid 5000 vmail 2>/dev/null || groupadd --system vmail
  fi
  if ! id vmail >/dev/null 2>&1; then
    useradd --system --uid 5000 --gid vmail --home /var/vmail --shell /usr/sbin/nologin vmail 2>/dev/null || \
      useradd --system --gid vmail --home /var/vmail --shell /usr/sbin/nologin vmail
  fi
  if ! id proidentity >/dev/null 2>&1; then
    useradd --system --home /opt/proidentity-mail --shell /usr/sbin/nologin proidentity
  fi
  gpasswd -d vmail proidentity >/dev/null 2>&1 || true
  usermod -a -G vmail proidentity || true
  usermod -a -G postfix proidentity || true
  usermod -a -G dovecot proidentity || true
}

write_units() {
  cat > /etc/systemd/system/proidentity-webadmin.service <<'UNIT'
[Unit]
Description=ProIdentity Mail Webadmin
After=network-online.target mariadb.service
Wants=network-online.target

[Service]
Type=simple
User=proidentity
Group=proidentity
SupplementaryGroups=postfix dovecot
EnvironmentFile=/etc/proidentity-mail/webadmin.env
ExecStart=/opt/proidentity-mail/bin/webadmin
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths=/etc/proidentity-mail

[Install]
WantedBy=multi-user.target
UNIT

  cat > /etc/systemd/system/proidentity-webmail.service <<'UNIT'
[Unit]
Description=ProIdentity Mail Webmail
After=network-online.target mariadb.service dovecot.service
Wants=network-online.target

[Service]
Type=simple
User=vmail
Group=vmail
EnvironmentFile=/etc/proidentity-mail/webmail.env
ExecStart=/opt/proidentity-mail/bin/webmail
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ReadWritePaths=/var/vmail

[Install]
WantedBy=multi-user.target
UNIT

  cat > /etc/systemd/system/proidentity-groupware.service <<'UNIT'
[Unit]
Description=ProIdentity Mail Groupware DAV
After=network-online.target mariadb.service
Wants=network-online.target

[Service]
Type=simple
User=proidentity
Group=proidentity
EnvironmentFile=/etc/proidentity-mail/groupware.env
ExecStart=/opt/proidentity-mail/bin/groupware
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ProtectHome=true

[Install]
WantedBy=multi-user.target
UNIT

  cat > /etc/systemd/system/proidentity-backup.service <<'UNIT'
[Unit]
Description=ProIdentity Mail Backup
Wants=mariadb.service
After=mariadb.service

[Service]
Type=oneshot
User=proidentity
Group=proidentity
EnvironmentFile=/etc/proidentity-mail/proidentity-mail.env
Environment=PROIDENTITY_BACKUP_DIR=/var/backups/proidentity-mail
Environment=PROIDENTITY_BACKUP_KEEP_DAILY=7
Environment=PROIDENTITY_BACKUP_KEEP_WEEKLY=4
Environment=PROIDENTITY_BACKUP_KEEP_MONTHLY=12
Environment=PROIDENTITY_BACKUP_SCHEDULED=1
ExecStart=/usr/bin/sudo -n -E /opt/proidentity-mail/bin/proidentity-rootctl backup
UMask=0077
NoNewPrivileges=false
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
PrivateDevices=true
RestrictSUIDSGID=false
LockPersonality=true
RestrictRealtime=true
RestrictNamespaces=true
SystemCallArchitectures=native
ReadWritePaths=/var/backups/proidentity-mail /tmp
ReadOnlyPaths=/etc/proidentity-mail /var/vmail /var/lib/proidentity-mail /var/lib/rspamd/dkim /etc/nginx /etc/letsencrypt
UNIT

  cat > /etc/systemd/system/proidentity-backup.timer <<'UNIT'
[Unit]
Description=Run ProIdentity Mail Backup Daily

[Timer]
OnCalendar=*-*-* 02:15:00
RandomizedDelaySec=20m
Persistent=true
Unit=proidentity-backup.service

[Install]
WantedBy=timers.target
UNIT

  cat > /etc/systemd/system/proidentity-tls-worker.service <<'UNIT'
[Unit]
Description=Process ProIdentity Mail TLS certificate jobs
Wants=network-online.target mariadb.service nginx.service
After=network-online.target mariadb.service nginx.service

[Service]
Type=oneshot
EnvironmentFile=/etc/proidentity-mail/proidentity-mail.env
ExecStart=/usr/bin/sudo -n -E /opt/proidentity-mail/bin/proidentity-rootctl tls-worker
User=proidentity
Group=proidentity
UMask=0077
NoNewPrivileges=false
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
PrivateDevices=true
RestrictSUIDSGID=false
LockPersonality=true
RestrictRealtime=true
RestrictNamespaces=true
SystemCallArchitectures=native
ReadWritePaths=/etc/proidentity-mail /etc/letsencrypt /etc/nginx /etc/postfix /etc/dovecot /var/lib/proidentity-mail/acme /var/lib/proidentity-mail /var/spool/postfix
UNIT

  cat > /etc/systemd/system/proidentity-tls-worker.timer <<'UNIT'
[Unit]
Description=Run ProIdentity Mail TLS worker every minute

[Timer]
OnBootSec=2m
OnUnitActiveSec=1m
Persistent=true
Unit=proidentity-tls-worker.service

[Install]
WantedBy=timers.target
UNIT

  cat > /etc/systemd/system/proidentity-config-apply.service <<'UNIT'
[Unit]
Description=Apply ProIdentity Mail live configuration
Wants=mariadb.service redis-server.service nginx.service
After=mariadb.service redis-server.service nginx.service

[Service]
Type=oneshot
User=proidentity
Group=proidentity
EnvironmentFile=/etc/proidentity-mail/proidentity-mail.env
ExecStart=/usr/bin/sudo -n -E /opt/proidentity-mail/bin/proidentity-rootctl config-apply
ExecStart=/usr/bin/sudo -n -E /opt/proidentity-mail/bin/proidentity-rootctl sync-proxy
UMask=0077
NoNewPrivileges=false
PrivateTmp=true
ProtectSystem=full
ProtectHome=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true
PrivateDevices=true
RestrictSUIDSGID=false
LockPersonality=true
RestrictRealtime=true
RestrictNamespaces=true
SystemCallArchitectures=native
ReadWritePaths=/etc/proidentity-mail /etc/nginx /etc/postfix /etc/dovecot /etc/rspamd /var/lib/rspamd/dkim /var/spool/postfix /var/lib/proidentity-mail/acme /var/lib/proidentity-mail /run /tmp
UNIT

  cat > /etc/systemd/system/proidentity-config-apply.path <<'UNIT'
[Unit]
Description=Watch ProIdentity Mail config apply requests

[Path]
PathChanged=/etc/proidentity-mail/apply-request
Unit=proidentity-config-apply.service

[Install]
WantedBy=multi-user.target
UNIT
}

ensure_placeholder_cert() {
  local host="$1"
  local live_dir="/etc/letsencrypt/live/${host}"
  if [[ -s "${live_dir}/fullchain.pem" && -s "${live_dir}/privkey.pem" ]]; then
    return
  fi
  install -d -m 0755 "${live_dir}"
  openssl req -x509 -newkey rsa:2048 -sha256 -days 7 -nodes \
    -subj "/CN=${host}" \
    -keyout "${live_dir}/privkey.pem" \
    -out "${live_dir}/fullchain.pem" >/dev/null 2>&1
  chmod 0600 "${live_dir}/privkey.pem"
}

write_env() {
  install -d -m 0750 -o root -g proidentity "${ENV_DIR}" "${ENV_DIR}/generated"
  touch "${ENV_FILE}"
  set -a
  # shellcheck disable=SC1090
  . "${ENV_FILE}" 2>/dev/null || true
  set +a

  install_env_file "${ENV_FILE}" root root 0600
  install_env_file "${ADMIN_ENV_FILE}" root proidentity 0640
  install_env_file "${WEBMAIL_ENV_FILE}" root vmail 0640
  install_env_file "${GROUPWARE_ENV_FILE}" root proidentity 0640

  DB_NAME="${DB_NAME:-${PROIDENTITY_DB_NAME:-proidentity_mail}}"
  DB_USER="${DB_USER:-${PROIDENTITY_DB_USER:-proidentity_mail}}"
  DB_PASSWORD="${DB_PASSWORD:-${PROIDENTITY_DB_PASSWORD:-$(random_secret 32)}}"
  BACKUP_ENCRYPTION_KEY="${BACKUP_ENCRYPTION_KEY:-${PROIDENTITY_BACKUP_ENCRYPTION_KEY:-$(random_secret 32)}}"
  AUTH_POLICY_TOKEN="${AUTH_POLICY_TOKEN:-${PROIDENTITY_AUTH_POLICY_TOKEN:-$(random_secret 32)}}"
  AUTH_POLICY_NONCE="${AUTH_POLICY_NONCE:-${PROIDENTITY_AUTH_POLICY_NONCE:-$(random_secret 32)}}"
  ADMIN_USERNAME="${ADMIN_USERNAME:-${PROIDENTITY_ADMIN_USERNAME:-admin}}"
  ADMIN_PASSWORD="${ADMIN_PASSWORD:-${PROIDENTITY_ADMIN_PASSWORD:-$(random_secret 24)}}"
  PUBLIC_IPV4="${PUBLIC_IPV4:-${PROIDENTITY_PUBLIC_IPV4:-$(detect_public_ipv4)}}"
  PUBLIC_IPV6="${PUBLIC_IPV6:-${PROIDENTITY_PUBLIC_IPV6:-}}"
  MAIL_HOSTNAME="${MAIL_HOSTNAME:-${PROIDENTITY_MAIL_HOSTNAME:-mail.local}}"
  ADMIN_HOSTNAME="${ADMIN_HOSTNAME:-${PROIDENTITY_ADMIN_HOSTNAME:-admin.${MAIL_HOSTNAME}}}"
  WEBMAIL_HOSTNAME="${WEBMAIL_HOSTNAME:-${PROIDENTITY_WEBMAIL_HOSTNAME:-webmail.${MAIL_HOSTNAME}}}"
  DAV_HOSTNAME="${DAV_HOSTNAME:-${PROIDENTITY_DAV_HOSTNAME:-${WEBMAIL_HOSTNAME}}}"
  PUBLIC_HOSTNAME="${PUBLIC_HOSTNAME:-${PROIDENTITY_PUBLIC_HOSTNAME:-}}"
  AUTOCONFIG_HOSTNAME="${AUTOCONFIG_HOSTNAME:-${PROIDENTITY_AUTOCONFIG_HOSTNAME:-$(default_discovery_hostname autoconfig)}}"
  AUTODISCOVER_HOSTNAME="${AUTODISCOVER_HOSTNAME:-${PROIDENTITY_AUTODISCOVER_HOSTNAME:-$(default_discovery_hostname autodiscover)}}"
  TLS_MODE="${TLS_MODE:-${PROIDENTITY_TLS_MODE:-none}}"
  PROXY_MODE="${PROXY_MODE:-${PROIDENTITY_PROXY_MODE:-internal-nginx}}"
  TRUST_PROXY_HEADERS="${TRUST_PROXY_HEADERS:-${PROIDENTITY_TRUST_PROXY_HEADERS:-false}}"
  TRUSTED_PROXY_CIDRS="${TRUSTED_PROXY_CIDRS:-${PROIDENTITY_TRUSTED_PROXY_CIDRS:-}}"
  CLOUDFLARE_CERT_DOMAIN="${CLOUDFLARE_CERT_DOMAIN:-${PROIDENTITY_CLOUDFLARE_CERT_DOMAIN:-}}"
  CLOUDFLARE_CREDENTIALS_FILE="${CLOUDFLARE_CREDENTIALS_FILE:-${PROIDENTITY_CLOUDFLARE_CREDENTIALS_FILE:-}}"
  TLS_CERT_PATH="${TLS_CERT_PATH:-${PROIDENTITY_TLS_CERT_PATH:-}}"
  TLS_KEY_PATH="${TLS_KEY_PATH:-${PROIDENTITY_TLS_KEY_PATH:-}}"

  validate_ident DB_NAME "${DB_NAME}"
  validate_ident DB_USER "${DB_USER}"
  case "${TLS_MODE}" in
    none|behind-proxy|letsencrypt-http|letsencrypt-dns-cloudflare|custom-cert) ;;
    *)
      echo "Unsupported TLS_MODE=${TLS_MODE}" >&2
      exit 2
      ;;
  esac
  case "${PROXY_MODE}" in
    internal-nginx) ;;
    *)
      echo "Unsupported PROXY_MODE=${PROXY_MODE}" >&2
      exit 2
      ;;
  esac

  local dsn="${DB_USER}:${DB_PASSWORD}@tcp(127.0.0.1:3306)/${DB_NAME}?parseTime=true&multiStatements=true"
  local secure_cookies="false"
  local force_https="false"
  if [[ "${TLS_MODE}" == "letsencrypt-http" || "${TLS_MODE}" == "letsencrypt-dns-cloudflare" || "${TLS_MODE}" == "custom-cert" || "${TLS_MODE}" == "behind-proxy" ]]; then
    secure_cookies="true"
  fi
  if [[ "${TLS_MODE}" == "letsencrypt-http" || "${TLS_MODE}" == "letsencrypt-dns-cloudflare" || "${TLS_MODE}" == "custom-cert" ]]; then
    force_https="true"
  fi
  if [[ "${TLS_MODE}" == "letsencrypt-http" || "${TLS_MODE}" == "letsencrypt-dns-cloudflare" ]]; then
    TLS_CERT_PATH="${TLS_CERT_PATH:-/etc/letsencrypt/live/${ADMIN_HOSTNAME}/fullchain.pem}"
    TLS_KEY_PATH="${TLS_KEY_PATH:-/etc/letsencrypt/live/${ADMIN_HOSTNAME}/privkey.pem}"
    ensure_placeholder_cert "${ADMIN_HOSTNAME}"
  fi
  if [[ "${TLS_MODE}" == "custom-cert" && ( -z "${TLS_CERT_PATH}" || -z "${TLS_KEY_PATH}" ) ]]; then
    echo "TLS_MODE=custom-cert requires TLS_CERT_PATH and TLS_KEY_PATH" >&2
    exit 2
  fi

  set_env PROIDENTITY_HTTP_ADDR "127.0.0.1:8080"
  set_env PROIDENTITY_GROUPWARE_ADDR "127.0.0.1:8081"
  set_env PROIDENTITY_WEBMAIL_ADDR "127.0.0.1:8082"
  set_env PROIDENTITY_DB_NAME "${DB_NAME}"
  set_env PROIDENTITY_DB_USER "${DB_USER}"
  set_env PROIDENTITY_DB_PASSWORD "${DB_PASSWORD}"
  set_env PROIDENTITY_DB_DSN "'${dsn}'"
  set_env PROIDENTITY_BACKUP_ENCRYPTION_KEY "${BACKUP_ENCRYPTION_KEY}"
  set_env PROIDENTITY_AUTH_POLICY_TOKEN "${AUTH_POLICY_TOKEN}"
  set_env PROIDENTITY_AUTH_POLICY_NONCE "${AUTH_POLICY_NONCE}"
  set_env PROIDENTITY_CONFIG_DIR "${ENV_DIR}/generated"
  set_env PROIDENTITY_MAILCTL_PATH "${BIN_DIR}/mailctl"
  set_env PROIDENTITY_CONFIG_APPLY_REQUEST_PATH "${ENV_DIR}/apply-request"
  set_env PROIDENTITY_QUARANTINE_DIR "/var/lib/proidentity-mail/quarantine"
  set_env PROIDENTITY_MAIL_ROOT "/var/vmail"
  set_env PROIDENTITY_RELEASE_SMTP_ADDR "127.0.0.1:25"
  set_env PROIDENTITY_MAIL_HOSTNAME "${MAIL_HOSTNAME}"
  set_env PROIDENTITY_PUBLIC_IPV4 "${PUBLIC_IPV4}"
  set_env PROIDENTITY_PUBLIC_IPV6 "${PUBLIC_IPV6}"
  set_env PROIDENTITY_PROXY_MODE "${PROXY_MODE}"
  set_env PROIDENTITY_TLS_MODE "${TLS_MODE}"
  set_env PROIDENTITY_PUBLIC_HOSTNAME "${PUBLIC_HOSTNAME}"
  set_env PROIDENTITY_ADMIN_HOSTNAME "${ADMIN_HOSTNAME}"
  set_env PROIDENTITY_WEBMAIL_HOSTNAME "${WEBMAIL_HOSTNAME}"
  set_env PROIDENTITY_DAV_HOSTNAME "${DAV_HOSTNAME}"
  set_env PROIDENTITY_AUTOCONFIG_HOSTNAME "${AUTOCONFIG_HOSTNAME}"
  set_env PROIDENTITY_AUTODISCOVER_HOSTNAME "${AUTODISCOVER_HOSTNAME}"
  set_env PROIDENTITY_ACME_WEBROOT "/var/lib/proidentity-mail/acme"
  set_env PROIDENTITY_TLS_CERT_PATH "${TLS_CERT_PATH}"
  set_env PROIDENTITY_TLS_KEY_PATH "${TLS_KEY_PATH}"
  set_env PROIDENTITY_MAIL_TLS_CERT_PATH "${TLS_CERT_PATH}"
  set_env PROIDENTITY_MAIL_TLS_KEY_PATH "${TLS_KEY_PATH}"
  set_env PROIDENTITY_CLOUDFLARE_CERT_DOMAIN "${CLOUDFLARE_CERT_DOMAIN}"
  set_env PROIDENTITY_CLOUDFLARE_CREDENTIALS_FILE "${CLOUDFLARE_CREDENTIALS_FILE}"
  set_env PROIDENTITY_TRUST_PROXY_HEADERS "${TRUST_PROXY_HEADERS}"
  set_env PROIDENTITY_TRUSTED_PROXY_CIDRS "${TRUSTED_PROXY_CIDRS}"
  set_env PROIDENTITY_FORCE_HTTPS "${force_https}"
  set_env PROIDENTITY_SECURE_COOKIES "${secure_cookies}"
  set_env PROIDENTITY_ADMIN_USERNAME "${ADMIN_USERNAME}"
  set_env PROIDENTITY_ADMIN_PASSWORD "${ADMIN_PASSWORD}"

  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_HTTP_ADDR "127.0.0.1:8080"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_DB_DSN "'${dsn}'"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_QUARANTINE_DIR "/var/lib/proidentity-mail/quarantine"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_MAIL_ROOT "/var/vmail"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_RELEASE_SMTP_ADDR "127.0.0.1:25"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_MAIL_HOSTNAME "${MAIL_HOSTNAME}"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_PUBLIC_IPV4 "${PUBLIC_IPV4}"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_PUBLIC_IPV6 "${PUBLIC_IPV6}"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_ADMIN_HOSTNAME "${ADMIN_HOSTNAME}"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_WEBMAIL_HOSTNAME "${WEBMAIL_HOSTNAME}"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_SECURE_COOKIES "${secure_cookies}"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_ADMIN_USERNAME "${ADMIN_USERNAME}"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_ADMIN_PASSWORD "${ADMIN_PASSWORD}"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_AUTH_POLICY_TOKEN "${AUTH_POLICY_TOKEN}"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_MAILCTL_PATH "${BIN_DIR}/mailctl"
  set_env_file "${ADMIN_ENV_FILE}" PROIDENTITY_CONFIG_APPLY_REQUEST_PATH "${ENV_DIR}/apply-request"

  set_env_file "${WEBMAIL_ENV_FILE}" PROIDENTITY_WEBMAIL_ADDR "127.0.0.1:8082"
  set_env_file "${WEBMAIL_ENV_FILE}" PROIDENTITY_DB_DSN "'${dsn}'"
  set_env_file "${WEBMAIL_ENV_FILE}" PROIDENTITY_MAIL_ROOT "/var/vmail"
  set_env_file "${WEBMAIL_ENV_FILE}" PROIDENTITY_SECURE_COOKIES "${secure_cookies}"

  set_env_file "${GROUPWARE_ENV_FILE}" PROIDENTITY_GROUPWARE_ADDR "127.0.0.1:8081"
  set_env_file "${GROUPWARE_ENV_FILE}" PROIDENTITY_DB_DSN "'${dsn}'"
  set_env_file "${GROUPWARE_ENV_FILE}" PROIDENTITY_SECURE_COOKIES "${secure_cookies}"
}

setup_database() {
  systemctl enable --now mariadb
  local db_password_sql
  db_password_sql="$(sql_string "${DB_PASSWORD}")"
  mariadb <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'127.0.0.1' IDENTIFIED BY ${db_password_sql};
ALTER USER '${DB_USER}'@'127.0.0.1' IDENTIFIED BY ${db_password_sql};
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';
FLUSH PRIVILEGES;
SQL
}

install_artifacts() {
  for name in webadmin webmail groupware mailctl apply-mail-config; do
    require_file "${ARTIFACT_DIR}/${name}"
  done
  install -d -m 0750 -o root -g proidentity /opt/proidentity-mail "${BIN_DIR}"
  install -m 0755 "${ARTIFACT_DIR}/webadmin" "${BIN_DIR}/webadmin"
  install -m 0755 "${ARTIFACT_DIR}/webmail" "${BIN_DIR}/webmail"
  install -m 0755 "${ARTIFACT_DIR}/groupware" "${BIN_DIR}/groupware"
  install -m 0755 "${ARTIFACT_DIR}/mailctl" "${BIN_DIR}/mailctl"
  install -m 0755 "${ARTIFACT_DIR}/apply-mail-config" "${BIN_DIR}/apply-mail-config"
  write_rootctl_helper
}

write_rootctl_helper() {
  cat > "${BIN_DIR}/proidentity-rootctl" <<'ROOTCTL'
#!/bin/sh
set -eu
PATH=/usr/sbin:/usr/bin:/sbin:/bin

case "${1:-}" in
  backup)
    exec /opt/proidentity-mail/bin/mailctl backup \
      --output-dir "${PROIDENTITY_BACKUP_DIR:-/var/backups/proidentity-mail}" \
      --prune-after \
      --keep-daily "${PROIDENTITY_BACKUP_KEEP_DAILY:-7}" \
      --keep-weekly "${PROIDENTITY_BACKUP_KEEP_WEEKLY:-4}" \
      --keep-monthly "${PROIDENTITY_BACKUP_KEEP_MONTHLY:-12}"
    ;;
  tls-worker)
    exec /opt/proidentity-mail/bin/mailctl process-tls-jobs --limit 3 --apply-config=true
    ;;
  config-apply)
    exec /opt/proidentity-mail/bin/apply-mail-config
    ;;
  sync-proxy)
    exec /opt/proidentity-mail/bin/mailctl sync-proxy --reload
    ;;
  *)
    echo "unsupported proidentity-rootctl command" >&2
    exit 64
    ;;
esac
ROOTCTL
  chown root:proidentity "${BIN_DIR}/proidentity-rootctl"
  chmod 0750 "${BIN_DIR}/proidentity-rootctl"
  cat > /etc/sudoers.d/proidentity-mail-rootctl <<EOF
Defaults:proidentity env_keep += "PROIDENTITY_*"
proidentity ALL=(root) NOPASSWD: ${BIN_DIR}/proidentity-rootctl backup
proidentity ALL=(root) NOPASSWD: ${BIN_DIR}/proidentity-rootctl tls-worker
proidentity ALL=(root) NOPASSWD: ${BIN_DIR}/proidentity-rootctl config-apply
proidentity ALL=(root) NOPASSWD: ${BIN_DIR}/proidentity-rootctl sync-proxy
EOF
  chmod 0440 /etc/sudoers.d/proidentity-mail-rootctl
  visudo -cf /etc/sudoers.d/proidentity-mail-rootctl >/dev/null
}

prepare_runtime_dirs() {
  install -d -m 0750 -o vmail -g vmail /var/vmail
  install -d -m 0750 -o root -g root /var/lib/proidentity-mail /var/lib/proidentity-mail/quarantine
  install -d -m 0700 -o root -g root /var/backups/proidentity-mail
  install -d -m 0755 -o root -g root /var/lib/proidentity-mail/acme
  install -d -m 0750 -o _rspamd -g _rspamd /var/lib/rspamd/dkim
  install -d -m 0750 -o root -g postfix /etc/postfix/proidentity
  install -d -m 0700 -o root -g root /etc/postfix/proidentity/tls-sni
  rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
}

issue_certificate_if_requested() {
  case "${TLS_MODE}" in
    letsencrypt-http)
      "${BIN_DIR}/mailctl" sync-proxy --reload
      "${BIN_DIR}/proidentity-issue-cert" || echo "warning: certbot HTTP challenge failed; placeholder certificate remains" >&2
      ;;
    letsencrypt-dns-cloudflare)
      if [[ -z "${CLOUDFLARE_CREDENTIALS_FILE}" || ! -s "${CLOUDFLARE_CREDENTIALS_FILE}" ]]; then
        echo "warning: Cloudflare credentials missing; DNS certificate not issued yet" >&2
      else
        "${BIN_DIR}/mailctl" sync-proxy --reload
        "${BIN_DIR}/proidentity-issue-cert" || echo "warning: certbot DNS challenge failed; placeholder certificate remains" >&2
      fi
      ;;
  esac
}

write_summary() {
  local web_scheme="http"
  if [[ "${TLS_MODE}" == "letsencrypt-http" || "${TLS_MODE}" == "letsencrypt-dns-cloudflare" || "${TLS_MODE}" == "custom-cert" || "${TLS_MODE}" == "behind-proxy" ]]; then
    web_scheme="https"
  fi
  cat > "${SUMMARY_FILE}" <<EOF
ProIdentity Mail setup summary
Generated at: $(date -Is)
Backup path: ${CONFIG_BACKUP_DIR}

Admin URL: ${web_scheme}://${ADMIN_HOSTNAME}/
Webmail URL: ${web_scheme}://${WEBMAIL_HOSTNAME}/
DAV URL: ${web_scheme}://${DAV_HOSTNAME}/dav/
Autoconfig host: ${AUTOCONFIG_HOSTNAME}
Autodiscover host: ${AUTODISCOVER_HOSTNAME}
Mail hostname: ${MAIL_HOSTNAME}
Public IPv4: ${PUBLIC_IPV4}
TLS mode: ${TLS_MODE}

Admin username: ${ADMIN_USERNAME}
Admin password: ${ADMIN_PASSWORD}

Database name: ${DB_NAME}
Database user: ${DB_USER}
Database password: ${DB_PASSWORD}
Backup encryption key: stored in ${ENV_FILE}
Environment file: ${ENV_FILE}
Webadmin environment file: ${ADMIN_ENV_FILE}
Webmail environment file: ${WEBMAIL_ENV_FILE}
Groupware environment file: ${GROUPWARE_ENV_FILE}

Important commands:
  source ${ENV_FILE}
  ${BIN_DIR}/mailctl migrate
  ${BIN_DIR}/apply-mail-config
  ${BIN_DIR}/mailctl sync-tls-inventory || true
  ${BIN_DIR}/mailctl sync-proxy --reload
  systemctl status proidentity-webadmin proidentity-webmail proidentity-groupware proidentity-tls-worker.timer proidentity-config-apply.path postfix dovecot rspamd nginx
EOF
  chmod 0600 "${SUMMARY_FILE}"
}

CONFIG_BACKUP_DIR="$(backup_existing)"
for name in webadmin webmail groupware mailctl apply-mail-config; do
  require_file "${ARTIFACT_DIR}/${name}"
done

MAIL_HOSTNAME="${MAIL_HOSTNAME:-${PROIDENTITY_MAIL_HOSTNAME:-mail.local}}"
install_packages
configure_dns_resolver
ensure_users
write_env
setup_database
install_artifacts
prepare_runtime_dirs
write_units

systemctl enable --now redis-server unbound postfix dovecot rspamd clamav-daemon nginx
systemctl daemon-reload
set -a
# shellcheck disable=SC1090
. "${ENV_FILE}"
set +a
"${BIN_DIR}/mailctl" migrate
"${BIN_DIR}/apply-mail-config"
"${BIN_DIR}/mailctl" sync-proxy --reload
issue_certificate_if_requested
"${BIN_DIR}/mailctl" sync-tls-inventory || true
"${BIN_DIR}/mailctl" sync-proxy --reload
systemctl enable --now proidentity-webadmin proidentity-webmail proidentity-groupware proidentity-backup.timer proidentity-tls-worker.timer proidentity-config-apply.path
systemctl restart proidentity-webadmin proidentity-webmail proidentity-groupware
write_summary

echo "ProIdentity Mail setup complete."
echo "Summary with generated secrets: ${SUMMARY_FILE}"
