package deploy_test

import (
	"os"
	"strings"
	"testing"
)

func TestProductionSetupExposesDiscoveryHostnames(t *testing.T) {
	scriptBytes, err := os.ReadFile("proidentity-production-setup.sh")
	if err != nil {
		t.Fatalf("read setup script: %v", err)
	}
	script := string(scriptBytes)

	for _, want := range []string{
		"AUTOCONFIG_HOSTNAME",
		"AUTODISCOVER_HOSTNAME",
		"PROIDENTITY_AUTOCONFIG_HOSTNAME",
		"PROIDENTITY_AUTODISCOVER_HOSTNAME",
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("setup script missing %s", want)
		}
	}

	runbookBytes, err := os.ReadFile("PRODUCTION_SETUP.md")
	if err != nil {
		t.Fatalf("read production setup runbook: %v", err)
	}
	runbook := string(runbookBytes)
	for _, want := range []string{"AUTOCONFIG_HOSTNAME", "AUTODISCOVER_HOSTNAME"} {
		if !strings.Contains(runbook, want) {
			t.Fatalf("production runbook missing %s", want)
		}
	}
}

func TestProductionSetupSupportsCLIOptionsAndAutogeneratedSecrets(t *testing.T) {
	scriptBytes, err := os.ReadFile("proidentity-production-setup.sh")
	if err != nil {
		t.Fatalf("read setup script: %v", err)
	}
	script := string(scriptBytes)
	for _, want := range []string{
		"Usage: proidentity-production-setup.sh [options]",
		"--artifact-dir PATH",
		"--mail-hostname HOST",
		"--admin-hostname HOST",
		"--webmail-hostname HOST",
		"--tls-mode MODE",
		"--db-password PASSWORD",
		"--backup-encryption-key SECRET",
		"parse_args \"$@\"",
		`DB_PASSWORD="${DB_PASSWORD:-${PROIDENTITY_DB_PASSWORD:-$(random_secret 32)}}"`,
		`BACKUP_ENCRYPTION_KEY="${BACKUP_ENCRYPTION_KEY:-${PROIDENTITY_BACKUP_ENCRYPTION_KEY:-$(random_secret 32)}}"`,
		`AUTH_POLICY_TOKEN="${AUTH_POLICY_TOKEN:-${PROIDENTITY_AUTH_POLICY_TOKEN:-$(random_secret 32)}}"`,
		`ADMIN_PASSWORD="${ADMIN_PASSWORD:-${PROIDENTITY_ADMIN_PASSWORD:-$(random_secret 24)}}"`,
		"Unsupported TLS_MODE",
		"Unsupported PROXY_MODE",
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("setup script missing CLI/autogen marker %s", want)
		}
	}

	runbookBytes, err := os.ReadFile("PRODUCTION_SETUP.md")
	if err != nil {
		t.Fatalf("read production setup runbook: %v", err)
	}
	runbook := string(runbookBytes)
	for _, want := range []string{
		"--artifact-dir /tmp/proidentity-release",
		"--mail-hostname mail.example.com",
		"Recommended: Install From Binary Release",
		"install-from-release.sh",
		"--github-repo Pro-IT-Services/ProIdentity-Mail",
		"BINARY_RELEASE_INSTALL.md",
		"Any omitted password, token, nonce, or backup key is generated",
		"`letsencrypt-http`: uses Let's Encrypt HTTP-01",
		"`letsencrypt-dns-cloudflare`: uses Let's Encrypt DNS-01",
	} {
		if !strings.Contains(runbook, want) {
			t.Fatalf("production runbook missing CLI setup marker %s", want)
		}
	}
}

func TestProductionSetupBindsBackendServicesToLoopback(t *testing.T) {
	scriptBytes, err := os.ReadFile("proidentity-production-setup.sh")
	if err != nil {
		t.Fatalf("read setup script: %v", err)
	}
	script := string(scriptBytes)

	for _, want := range []string{
		`set_env PROIDENTITY_HTTP_ADDR "127.0.0.1:8080"`,
		`set_env PROIDENTITY_GROUPWARE_ADDR "127.0.0.1:8081"`,
		`set_env PROIDENTITY_WEBMAIL_ADDR "127.0.0.1:8082"`,
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("setup script missing loopback bind %s", want)
		}
	}
	for _, disallowed := range []string{
		`set_env PROIDENTITY_HTTP_ADDR "0.0.0.0:8080"`,
		`set_env PROIDENTITY_GROUPWARE_ADDR "0.0.0.0:8081"`,
		`set_env PROIDENTITY_WEBMAIL_ADDR "0.0.0.0:8082"`,
	} {
		if strings.Contains(script, disallowed) {
			t.Fatalf("setup script still exposes backend bind %s", disallowed)
		}
	}
}

func TestProductionSetupConfiguresDNSBLSafeResolver(t *testing.T) {
	scriptBytes, err := os.ReadFile("proidentity-production-setup.sh")
	if err != nil {
		t.Fatalf("read setup script: %v", err)
	}
	script := string(scriptBytes)

	for _, want := range []string{
		"unbound dns-root-data",
		"configure_dns_resolver",
		"/etc/unbound/unbound.conf.d/proidentity-dnsbl.conf",
		"nameserver 127.0.0.1",
		"nameserver 1.1.1.1",
		"nameserver 8.8.8.8",
		"systemctl enable --now redis-server unbound postfix",
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("setup script missing DNSBL resolver setup %s", want)
		}
	}
}

func TestProductionSetupIncludesConfigApplyQueue(t *testing.T) {
	scriptBytes, err := os.ReadFile("proidentity-production-setup.sh")
	if err != nil {
		t.Fatalf("read setup script: %v", err)
	}
	script := string(scriptBytes)

	for _, want := range []string{
		"proidentity-config-apply.service",
		"proidentity-config-apply.path",
		"PathChanged=/etc/proidentity-mail/apply-request",
		"ExecStart=/usr/bin/sudo -n /opt/proidentity-mail/bin/proidentity-rootctl config-apply",
		"ExecStart=/usr/bin/sudo -n /opt/proidentity-mail/bin/proidentity-rootctl sync-proxy",
		`install -m 0660 -o proidentity -g proidentity /dev/null "${ENV_DIR}/apply-request"`,
		"systemctl enable --now proidentity-webadmin proidentity-webmail proidentity-groupware proidentity-backup.timer proidentity-tls-worker.timer proidentity-config-apply.path",
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("setup script missing config apply queue %s", want)
		}
	}
}

func TestProductionSetupSeparatesServiceSecrets(t *testing.T) {
	scriptBytes, err := os.ReadFile("proidentity-production-setup.sh")
	if err != nil {
		t.Fatalf("read setup script: %v", err)
	}
	script := string(scriptBytes)

	for _, want := range []string{
		`ADMIN_ENV_FILE="${ADMIN_ENV_FILE:-${ENV_DIR}/webadmin.env}"`,
		`WEBMAIL_ENV_FILE="${WEBMAIL_ENV_FILE:-${ENV_DIR}/webmail.env}"`,
		`GROUPWARE_ENV_FILE="${GROUPWARE_ENV_FILE:-${ENV_DIR}/groupware.env}"`,
		`EnvironmentFile=/etc/proidentity-mail/webadmin.env`,
		`EnvironmentFile=/etc/proidentity-mail/webmail.env`,
		`EnvironmentFile=/etc/proidentity-mail/groupware.env`,
		`install_env_file "${ENV_FILE}" root root 0600`,
		`install_env_file "${WEBMAIL_ENV_FILE}" root vmail 0640`,
		`gpasswd -d vmail proidentity`,
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("setup script missing secret isolation marker %s", want)
		}
	}

	for _, disallowed := range []string{
		`usermod -a -G proidentity vmail`,
		`SupplementaryGroups=proidentity`,
		`EnvironmentFile=/etc/proidentity-mail/proidentity-mail.env
ExecStart=/opt/proidentity-mail/bin/webmail`,
	} {
		if strings.Contains(script, disallowed) {
			t.Fatalf("setup script still exposes webmail to shared secrets: %s", disallowed)
		}
	}
}

func TestProductionSetupKeepsBackupsRootOnly(t *testing.T) {
	scriptBytes, err := os.ReadFile("proidentity-production-setup.sh")
	if err != nil {
		t.Fatalf("read setup script: %v", err)
	}
	script := string(scriptBytes)
	if !strings.Contains(script, `install -d -m 0700 -o root -g root /var/backups/proidentity-mail`) {
		t.Fatalf("setup script must keep backup directory root-only")
	}
	if strings.Contains(script, `install -d -m 0750 -o root -g root /var/lib/proidentity-mail /var/lib/proidentity-mail/quarantine /var/backups/proidentity-mail`) {
		t.Fatalf("backup directory is still grouped with broader runtime directories")
	}
	for _, want := range []string{
		`install -d -m 0751 -o root -g root /var/lib/proidentity-mail`,
		`install -d -m 0750 -o root -g root /var/lib/proidentity-mail/quarantine`,
		`install -d -m 0755 -o root -g root /var/lib/proidentity-mail/acme`,
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("setup script missing ACME/quarantine permission marker %s", want)
		}
	}
	if !strings.Contains(script, "Environment=PROIDENTITY_BACKUP_SCHEDULED=1") {
		t.Fatalf("backup service should mark timer-backed runs for audit")
	}
	unitBytes, err := os.ReadFile("devmail/proidentity-backup.service")
	if err != nil {
		t.Fatalf("read dev backup service: %v", err)
	}
	if !strings.Contains(string(unitBytes), "Environment=PROIDENTITY_BACKUP_SCHEDULED=1") {
		t.Fatalf("dev backup service should mark timer-backed runs for audit")
	}
}

func TestRootOneshotUnitsUseSystemdSandboxing(t *testing.T) {
	scriptBytes, err := os.ReadFile("proidentity-production-setup.sh")
	if err != nil {
		t.Fatalf("read setup script: %v", err)
	}
	script := string(scriptBytes)
	for _, want := range []string{
		"ProtectKernelTunables=true",
		"ProtectKernelModules=true",
		"ProtectControlGroups=true",
		"PrivateDevices=true",
		"LockPersonality=true",
		"RestrictRealtime=true",
		"RestrictNamespaces=true",
		"SystemCallArchitectures=native",
	} {
		if strings.Count(script, want) < 3 {
			t.Fatalf("root oneshot units should all include %s", want)
		}
	}
	for _, path := range []string{"devmail/proidentity-backup.service", "devmail/proidentity-config-apply.service"} {
		unitBytes, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		unit := string(unitBytes)
		for _, want := range []string{"ProtectKernelTunables=true", "PrivateDevices=true", "SystemCallArchitectures=native"} {
			if !strings.Contains(unit, want) {
				t.Fatalf("%s missing systemd sandboxing marker %s", path, want)
			}
		}
	}
}

func TestPrivilegedJobsUseScopedRootHelper(t *testing.T) {
	scriptBytes, err := os.ReadFile("proidentity-production-setup.sh")
	if err != nil {
		t.Fatalf("read setup script: %v", err)
	}
	script := string(scriptBytes)
	for _, want := range []string{
		"write_rootctl_helper",
		"/etc/sudoers.d/proidentity-mail-rootctl",
		`Defaults:proidentity env_keep += "PROIDENTITY_*"`,
		"proidentity ALL=(root) NOPASSWD: ${BIN_DIR}/proidentity-rootctl backup",
		"proidentity ALL=(root) NOPASSWD: ${BIN_DIR}/proidentity-rootctl tls-worker",
		"proidentity ALL=(root) NOPASSWD: ${BIN_DIR}/proidentity-rootctl config-apply",
		"proidentity ALL=(root) NOPASSWD: ${BIN_DIR}/proidentity-rootctl sync-proxy",
		"ExecStart=/usr/bin/sudo -n /opt/proidentity-mail/bin/proidentity-rootctl backup",
		"ExecStart=/usr/bin/sudo -n /opt/proidentity-mail/bin/proidentity-rootctl tls-worker",
		"ExecStart=/usr/bin/sudo -n /opt/proidentity-mail/bin/proidentity-rootctl config-apply",
		"ExecStart=/usr/bin/sudo -n /opt/proidentity-mail/bin/proidentity-rootctl sync-proxy",
		"ReadWritePaths=/etc/proidentity-mail /etc/letsencrypt /etc/nginx /etc/postfix /etc/dovecot /etc/rspamd /var/lib/rspamd/dkim /var/lib/proidentity-mail/acme /var/lib/proidentity-mail /var/spool/postfix /run /tmp",
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("production setup missing scoped root helper marker %s", want)
		}
	}
	for _, disallowed := range []string{
		"ExecStart=/opt/proidentity-mail/bin/mailctl backup",
		"ExecStart=/opt/proidentity-mail/bin/mailctl process-tls-jobs",
		"ExecStart=/opt/proidentity-mail/bin/apply-mail-config",
	} {
		if strings.Contains(script, disallowed) {
			t.Fatalf("privileged service still calls root command directly: %s", disallowed)
		}
	}
	for _, path := range []string{"devmail/proidentity-backup.service", "devmail/proidentity-config-apply.service"} {
		unitBytes, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		unit := string(unitBytes)
		for _, want := range []string{"User=proidentity", "/usr/bin/sudo -n /opt/proidentity-mail/bin/proidentity-rootctl"} {
			if !strings.Contains(unit, want) {
				t.Fatalf("%s missing scoped root helper marker %s", path, want)
			}
		}
	}
	rootctlBytes, err := os.ReadFile("devmail/proidentity-rootctl")
	if err != nil {
		t.Fatalf("read dev root helper: %v", err)
	}
	rootctl := string(rootctlBytes)
	for _, want := range []string{"backup)", "tls-worker)", "config-apply)", "sync-proxy)", "exit 64"} {
		if !strings.Contains(rootctl, want) {
			t.Fatalf("dev root helper missing allowlist command %s", want)
		}
	}
	setupBytes, err := os.ReadFile("devmail/setup-runtime.sh")
	if err != nil {
		t.Fatalf("read dev setup runtime: %v", err)
	}
	setup := string(setupBytes)
	for _, want := range []string{"/etc/sudoers.d/proidentity-mail-rootctl", "visudo -cf", "install -m 0750 /tmp/proidentity-devmail/proidentity-rootctl"} {
		if !strings.Contains(setup, want) {
			t.Fatalf("dev runtime setup missing root helper marker %s", want)
		}
	}
	for _, want := range []string{
		"install -d -m 0755 -o root -g root /opt/proidentity-mail",
		"chmod 0755 /opt/proidentity-mail /opt/proidentity-mail/bin",
	} {
		if !strings.Contains(script+setup, want) {
			t.Fatalf("runtime setup missing executable directory access marker %s", want)
		}
	}
}

func TestProductionRunbookIncludesSecurityCheckScript(t *testing.T) {
	scriptBytes, err := os.ReadFile("../scripts/security-check.ps1")
	if err != nil {
		t.Fatalf("read security check script: %v", err)
	}
	script := string(scriptBytes)
	for _, want := range []string{"go test ./...", "go list -m all", "govulncheck"} {
		if !strings.Contains(script, want) {
			t.Fatalf("security check script missing %s", want)
		}
	}
	runbookBytes, err := os.ReadFile("PRODUCTION_SETUP.md")
	if err != nil {
		t.Fatalf("read production setup runbook: %v", err)
	}
	if !strings.Contains(string(runbookBytes), `.\scripts\security-check.ps1`) {
		t.Fatalf("production runbook should include security-check.ps1")
	}
	workflowBytes, err := os.ReadFile("../.github/workflows/security-check.yml")
	if err != nil {
		t.Fatalf("read security check workflow: %v", err)
	}
	workflow := string(workflowBytes)
	for _, want := range []string{"Security Check", "actions/setup-go@v5", "scripts\\security-check.ps1"} {
		if !strings.Contains(workflow, want) {
			t.Fatalf("security check workflow missing %s", want)
		}
	}
	exceptionBytes, err := os.ReadFile("../docs/security/DEPENDENCY_EXCEPTION_PROCESS.md")
	if err != nil {
		t.Fatalf("read dependency exception process: %v", err)
	}
	exceptionProcess := string(exceptionBytes)
	for _, want := range []string{"No exception is allowed", "Expires:", "no reachable High or Critical dependency vulnerabilities may ship"} {
		if !strings.Contains(exceptionProcess, want) {
			t.Fatalf("dependency exception process missing %s", want)
		}
	}
}

func TestPublicReleaseLicenseAndBinaryInstallArtifacts(t *testing.T) {
	for path, markers := range map[string][]string{
		"../LICENSE": {
			"ProIdentity Mail Dual License",
			"Commercial Hosted Service Use",
			"GNU Affero General Public License version 3",
			"requires a separate written commercial license",
		},
		"../COMMERCIAL-LICENSE.md": {
			"Commercial Hosted Service Use",
			"hosted mail or groupware service",
			"cloud marketplace image",
		},
		"../README.md": {
			"Binary Install from GitHub Release",
			"Commercial hosted service use requires a separate commercial license",
			"proidentity-mail_<version>_linux_x64.tar.gz",
		},
		"BINARY_RELEASE_INSTALL.md": {
			"without compiling Go code on the server",
			"installs packages",
			"proidentity-production-setup.sh",
			"proidentity-mail_<version>_linux_arm64.tar.gz",
			"--github-repo Pro-IT-Services/ProIdentity-Mail",
		},
		"../.github/workflows/release.yml": {
			"Release",
			"actions/setup-go@v5",
			"bash scripts/build-release.sh",
			"actions/upload-artifact@v4",
			"softprops/action-gh-release@v2",
		},
		"../.gitlab-ci.yml": {
			"build-release",
			"govulncheck",
			"proidentity-mail_${CI_COMMIT_TAG}_linux_x64.tar.gz",
			"proidentity-mail_${CI_COMMIT_TAG}_linux_x86.tar.gz",
			"proidentity-mail_${CI_COMMIT_TAG}_linux_arm.tar.gz",
			"proidentity-mail_${CI_COMMIT_TAG}_linux_arm64.tar.gz",
		},
		"../scripts/build-release.sh": {
			"linux amd64 '' x64",
			"linux 386 '' x86",
			"linux arm 7 arm",
			"linux arm64 '' arm64",
			"proidentity-production-setup.sh",
			"apply-mail-config",
		},
		"install-from-release.sh": {
			"--github-repo OWNER/REPO",
			"--gitlab-project-id ID",
			"--release-url URL",
			"detect_target",
			"require_root",
			"must be run as root",
			"${GITHUB_REPO}/releases/download/${VERSION}",
			"proidentity-production-setup.sh\" --artifact-dir",
			"will install packages and configure the full server",
		},
	} {
		bytes, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read %s: %v", path, err)
		}
		content := string(bytes)
		for _, marker := range markers {
			if !strings.Contains(content, marker) {
				t.Fatalf("%s missing release marker %s", path, marker)
			}
		}
	}

	installerBytes, err := os.ReadFile("install-from-release.sh")
	if err != nil {
		t.Fatalf("read install-from-release.sh: %v", err)
	}
	if strings.Contains(string(installerBytes), "go build") {
		t.Fatalf("binary release installer must not compile on the target server")
	}

	setupBytes, err := os.ReadFile("proidentity-production-setup.sh")
	if err != nil {
		t.Fatalf("read proidentity-production-setup.sh: %v", err)
	}
	setup := string(setupBytes)
	for _, want := range []string{
		"install_packages",
		"apt-get update",
		"apt-get install -y",
		"mariadb-server",
		"postfix",
		"dovecot-imapd",
		"rspamd",
		"clamav-daemon",
		"nginx",
		"unbound",
	} {
		if !strings.Contains(setup, want) {
			t.Fatalf("release bootstrap missing package/setup marker %s", want)
		}
	}
}

func TestApplyMailConfigInstallsAllRspamdRenderedPolicyFiles(t *testing.T) {
	scriptBytes, err := os.ReadFile("devmail/apply-mail-config.sh")
	if err != nil {
		t.Fatalf("read apply script: %v", err)
	}
	script := string(scriptBytes)

	for _, want := range []string{
		"rspamd-local.d-settings.conf /etc/rspamd/local.d/settings.conf",
		"rspamd-local.d-force_actions.conf /etc/rspamd/local.d/force_actions.conf",
	} {
		if !strings.Contains(script, want) {
			t.Fatalf("apply script missing rspamd policy install %s", want)
		}
	}
}
