CREATE TABLE domain_tls_settings (
  domain_id bigint unsigned NOT NULL PRIMARY KEY,
  dns_webmail_alias_enabled tinyint(1) NOT NULL DEFAULT 1,
  dns_admin_alias_enabled tinyint(1) NOT NULL DEFAULT 1,
  tls_mode enum('inherit','letsencrypt-dns-cloudflare','letsencrypt-http','custom','disabled') NOT NULL DEFAULT 'inherit',
  challenge_type enum('dns-cloudflare','http-01','manual-dns','custom-import','none') NOT NULL DEFAULT 'dns-cloudflare',
  use_for_https tinyint(1) NOT NULL DEFAULT 1,
  use_for_mail_sni tinyint(1) NOT NULL DEFAULT 1,
  include_mail_hostname tinyint(1) NOT NULL DEFAULT 1,
  include_webmail_hostname tinyint(1) NOT NULL DEFAULT 1,
  include_admin_hostname tinyint(1) NOT NULL DEFAULT 1,
  certificate_name varchar(253) NOT NULL DEFAULT '',
  custom_cert_path varchar(500) NOT NULL DEFAULT '',
  custom_key_path varchar(500) NOT NULL DEFAULT '',
  custom_chain_path varchar(500) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  CONSTRAINT domain_tls_settings_domain_id_fk FOREIGN KEY (domain_id) REFERENCES domains(id)
);

CREATE TABLE tls_certificates (
  id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  domain_id bigint unsigned NOT NULL,
  source enum('letsencrypt','custom','system') NOT NULL DEFAULT 'letsencrypt',
  status enum('missing','pending','issuing','active','expiring','expired','failed','disabled') NOT NULL DEFAULT 'missing',
  common_name varchar(253) NOT NULL DEFAULT '',
  sans_json json NOT NULL,
  cert_path varchar(500) NOT NULL DEFAULT '',
  key_path varchar(500) NOT NULL DEFAULT '',
  chain_path varchar(500) NOT NULL DEFAULT '',
  issuer varchar(500) NOT NULL DEFAULT '',
  serial varchar(160) NOT NULL DEFAULT '',
  fingerprint_sha256 varchar(95) NOT NULL DEFAULT '',
  not_before timestamp NULL,
  not_after timestamp NULL,
  used_for_https tinyint(1) NOT NULL DEFAULT 0,
  used_for_mail_sni tinyint(1) NOT NULL DEFAULT 0,
  last_error varchar(1000) NOT NULL DEFAULT '',
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  KEY tls_certificates_domain_status_idx (domain_id, status),
  KEY tls_certificates_not_after_idx (not_after),
  CONSTRAINT tls_certificates_domain_id_fk FOREIGN KEY (domain_id) REFERENCES domains(id)
);

CREATE TABLE tls_certificate_jobs (
  id bigint unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  domain_id bigint unsigned NOT NULL,
  certificate_id bigint unsigned NULL,
  job_type enum('issue','renew','import','deploy','check') NOT NULL DEFAULT 'issue',
  challenge_type enum('dns-cloudflare','http-01','manual-dns','custom-import','none') NOT NULL DEFAULT 'dns-cloudflare',
  status enum('queued','running','succeeded','failed','cancelled') NOT NULL DEFAULT 'queued',
  step varchar(120) NOT NULL DEFAULT 'queued',
  progress tinyint unsigned NOT NULL DEFAULT 0,
  message varchar(1000) NOT NULL DEFAULT '',
  error varchar(1000) NOT NULL DEFAULT '',
  hostnames_json json NOT NULL,
  log_json json NOT NULL,
  requested_by varchar(190) NOT NULL DEFAULT '',
  started_at timestamp NULL,
  finished_at timestamp NULL,
  created_at timestamp NOT NULL DEFAULT current_timestamp(),
  updated_at timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  KEY tls_certificate_jobs_domain_created_idx (domain_id, created_at),
  KEY tls_certificate_jobs_status_created_idx (status, created_at),
  CONSTRAINT tls_certificate_jobs_domain_id_fk FOREIGN KEY (domain_id) REFERENCES domains(id),
  CONSTRAINT tls_certificate_jobs_certificate_id_fk FOREIGN KEY (certificate_id) REFERENCES tls_certificates(id)
);
